// This file is auto-generated by scripts/scrape-fallbacks.mjs
export const FALLBACK_IMAGES = [
  "https://i.ibb.co/qL1y0DYT/fallback-image-1.avif",
  "https://i.ibb.co/0yY9f4Rq/fallback-image-2.avif",
  "https://i.ibb.co/8HtTqx4/fallback-image-3.avif",
  "https://i.ibb.co/FLNr5phq/fallback-image-4.avif",
  "https://i.ibb.co/Y7yQ0ZTf/fallback-image-5.avif",
  "https://i.ibb.co/vCMqdCYs/fallback-image-6.avif",
  "https://i.ibb.co/0jhmvZy2/fallback-image-7.avif",
  "https://i.ibb.co/YFnJ7YXH/fallback-image-8.avif",
  "https://i.ibb.co/4RT9MfN5/fallback-image-9.avif",
  "https://i.ibb.co/r24RDGxn/fallback-image-10.avif",
  "https://i.ibb.co/WNncR1Ck/fallback-image-11.avif",
  "https://i.ibb.co/ycjcPpqV/fallback-image-12.avif",
  "https://i.ibb.co/Y4YzwxXp/fallback-image-13.avif",
  "https://i.ibb.co/4RgCpq73/fallback-image-14.avif",
  "https://i.ibb.co/yM09gwQ/fallback-image-15.avif",
  "https://i.ibb.co/tpnsLmcM/fallback-image-16.avif",
  "https://i.ibb.co/Q72JNbJD/fallback-image-17.avif",
  "https://i.ibb.co/ZzXDgM4x/fallback-image-18.avif",
  "https://i.ibb.co/fTZ9gF8/fallback-image-19.avif",
  "https://i.ibb.co/WpNMsX9M/fallback-image-20.avif",
  "https://i.ibb.co/hFNRzbnN/fallback-image-21.avif",
  "https://i.ibb.co/n87YvJXR/fallback-image-22.avif",
  "https://i.ibb.co/ym2p170k/fallback-image-23.avif",
  "https://i.ibb.co/g07VLP1/fallback-image-24.avif",
  "https://i.ibb.co/KzbhMS8s/fallback-image-25.avif",
  "https://i.ibb.co/DPgzGwnb/fallback-image-26.avif",
  "https://i.ibb.co/20fGrBZX/fallback-image-27.avif",
  "https://i.ibb.co/LdMcPSg8/fallback-image-28.avif",
  "https://i.ibb.co/1f9V80dF/fallback-image-29.avif",
  "https://i.ibb.co/bfqqgFn/fallback-image-30.avif",
  "https://i.ibb.co/F4kDL2NW/fallback-image-31.avif",
  "https://i.ibb.co/5xj1XkyG/fallback-image-32.avif",
  "https://i.ibb.co/7tvcZsKs/fallback-image-33.avif",
  "https://i.ibb.co/0jrg62jc/fallback-image-34.avif",
  "https://i.ibb.co/v4cYSTNM/fallback-image-35.avif",
  "https://i.ibb.co/3yzMSjzs/fallback-image-36.avif",
  "https://i.ibb.co/YBSrpZZW/fallback-image-37.avif",
  "https://i.ibb.co/Ld7JQFXB/fallback-image-38.avif",
  "https://i.ibb.co/DgY0kCMc/fallback-image-39.avif",
  "https://i.ibb.co/TNfSP25/fallback-image-40.avif",
  "https://i.ibb.co/LdBCCdVq/fallback-image-41.avif",
  "https://i.ibb.co/Jjjw7GY8/fallback-image-42.avif",
  "https://i.ibb.co/ztpWRsm/fallback-image-43.avif",
  "https://i.ibb.co/Q7ch0GGq/fallback-image-44.avif",
  "https://i.ibb.co/6RKYfXrT/fallback-image-45.avif",
  "https://i.ibb.co/DDXNV3Gg/fallback-image-46.avif",
  "https://i.ibb.co/vvR4X2NY/fallback-image-47.avif",
  "https://i.ibb.co/2Yy1SXN0/fallback-image-48.avif",
  "https://i.ibb.co/Sgh1WBj/fallback-image-49.avif",
  "https://i.ibb.co/ZvDRPBV/fallback-image-50.avif",
  "https://i.ibb.co/PZq5vx9r/fallback-image-51.avif",
  "https://i.ibb.co/Qvk8x6Gy/fallback-image-52.avif",
  "https://i.ibb.co/6036s2rM/fallback-image-53.avif"
] as const;

export const getRandomFallback = () => {
  const randomIndex = Math.floor(Math.random() * FALLBACK_IMAGES.length);
  return FALLBACK_IMAGES[randomIndex];
};

export const getFallbackBySlug = (slug: string = '') => {
  if (!slug) return getRandomFallback();

  let hash = 0;
  for (let i = 0; i < slug.length; i++) {
    hash = slug.charCodeAt(i) + ((hash << 5) - hash);
  }

  const index = Math.abs(hash % FALLBACK_IMAGES.length);
  return FALLBACK_IMAGES[index];
};
