/**
 * Integration test: verifies that URLs generated by getCloudinaryOgWithTitle
 * actually resolve with HTTP 200 from Cloudinary (no invalid params, font exists).
 *
 * Requires network access. Skipped in CI if CLOUDINARY_URL is not set.
 */
import { describe, it, expect } from 'vitest'
import { getCloudinaryOgWithTitle } from '../../../src/utilities/cloudinaryUrl'

// A real fallback image from the project used as a stable test fixture
const REAL_CLOUDINARY_URL =
  'https://res.cloudinary.com/dmufha3qv/image/upload/v1770675714/portfolio/fallback-image-30.avif'

async function httpStatus(url: string): Promise<{ status: number; cldError: string | null }> {
  const res = await fetch(url, { method: 'HEAD' })
  return {
    status: res.status,
    cldError: res.headers.get('x-cld-error'),
  }
}

describe('getCloudinaryOgWithTitle — live Cloudinary validation', () => {
  it('generates a valid 200 URL for a simple ASCII title', async () => {
    const url = getCloudinaryOgWithTitle(REAL_CLOUDINARY_URL, 'Hello World')
    const { status, cldError } = await httpStatus(url)
    expect(cldError, `Cloudinary error: ${cldError}`).toBeNull()
    expect(status).toBe(200)
  })

  it('generates a valid 200 URL for a Spanish title with accents', async () => {
    const url = getCloudinaryOgWithTitle(
      REAL_CLOUDINARY_URL,
      'Guía Definitiva de SEO para Desarrolladores',
    )
    const { status, cldError } = await httpStatus(url)
    expect(cldError, `Cloudinary error: ${cldError}`).toBeNull()
    expect(status).toBe(200)
  })

  it('generates a valid 200 URL for a title with colon and special chars', async () => {
    // Mirrors the real-world title from the user's example URL
    const url = getCloudinaryOgWithTitle(
      REAL_CLOUDINARY_URL,
      'SQL vs NoSQL: Comparativa y Guía de Decisión para Desarrolladores',
    )
    const { status, cldError } = await httpStatus(url)
    expect(cldError, `Cloudinary error: ${cldError}`).toBeNull()
    expect(status).toBe(200)
  })

  it('generates a valid 200 URL for a title that gets truncated (>65 chars)', async () => {
    const longTitle =
      'The Complete and Definitive Guide to Modern Software Architecture Patterns in 2026'
    const url = getCloudinaryOgWithTitle(REAL_CLOUDINARY_URL, longTitle)
    const { status, cldError } = await httpStatus(url)
    expect(cldError, `Cloudinary error: ${cldError}`).toBeNull()
    expect(status).toBe(200)
  })

  it('returns HTTP 200 for a URL that already has existing transformations', async () => {
    const alreadyTransformed =
      'https://res.cloudinary.com/dmufha3qv/image/upload/f_avif,q_auto/v1770675714/portfolio/fallback-image-30.avif'
    const url = getCloudinaryOgWithTitle(alreadyTransformed, 'Strip and Rebuild')
    const { status, cldError } = await httpStatus(url)
    expect(cldError, `Cloudinary error: ${cldError}`).toBeNull()
    expect(status).toBe(200)
  })

  it('output URL contains the correct JPEG format header', async () => {
    const url = getCloudinaryOgWithTitle(REAL_CLOUDINARY_URL, 'Format Check')
    const res = await fetch(url, { method: 'HEAD' })
    expect(res.headers.get('content-type')).toContain('image/jpeg')
  })
})
